# Generated by Django 4.2 on 2023-04-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_usermodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_admin',
        ),
    ]
