# Generated by Django 4.2 on 2023-04-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_usermodel_is_active_remove_usermodel_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
    ]
