# Generated by Django 4.2 on 2023-04-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_usermodel_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='LikeModel',
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
