# Generated by Django 3.2.15 on 2023-04-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_postmodel_likemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likemodel',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likemodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
